# ----- general -----
bindkey -v # vim key bindings

# ----- (16.2.1) changing directories-----
setopt autocd

# ----- (16.2.2) completion -----
setopt menucomplete


# ----- (16.2.4) history -----
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

setopt incappendhistorytime
setopt extended_history
setopt banghist
setopt histverify
setopt histfindnodups
setopt histignorespace

bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# ----- ## -----
setopt correct

setopt beep extendedglob nomatch notify promptsubst

# The following lines were added by compinstall
zstyle :compinstall filename "/Users/jnk/.zshrc"

autoload -Uz compinit
compinit -u
# End of lines added by compinstall

zstyle ":completion:*" menu select interactive

# personal settings
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
#export PATH:"$PATH:/Applications/microchip/xc32/v1.33/bin"

export EDITOR="vim"

export CLICOLOR=true # ls coloured output

alias l="ls -h"
alias ll="ls -ah"
alias lll="ls -lah"

alias h='history -t "%T"'
alias hh='history -t "%a %d.%m.%Y %T" -D'
alias h1='history -t "%a %d.%m.%Y %T" -D -1'

alias pi="ping example.com"
alias fucking="sudo"

alias vim="nvim"

#alias mat="matlab -nojvm -nosidplay"

bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word

# end personal settings

# custom prompt
. $HOME/.config/zsh/prompt.zsh

# disable empty commands
accept-nonempty-line () {
	if [[ -n $BUFFER ]] then
		unset RESPONSIVE_TEST
		zle reset-prompt
		zle accept-line
	else
		if [[ -z $RESPONSIVE_TEST ]] then
			RESPONSIVE_TEST=true
			RESPONSIVE_TEST_CYCLE=0
		else
			RESPONSIVE_TEST_CYCLE=$((($RESPONSIVE_TEST_CYCLE + 1) % 4))
		fi

		zle reset-prompt
	fi
}

zle -N accept-nonempty-line
bindkey "^M" accept-nonempty-line


GREP_OPTIONS='--color=auto'

# OPAM configuration
. ${HOME}/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# iTerm2 shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
