# ----- general -----
bindkey -v # vim key bindings

# ----- (16.2.1) changing directories-----
setopt autocd

# ----- (16.2.2) completion -----
setopt menucomplete


# ----- (16.2.4) history -----
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

setopt incappendhistorytime
setopt extended_history
setopt banghist
setopt histverify
setopt histfindnodups
setopt histignorespace

bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# ----- ## -----
setopt correct

setopt beep extendedglob nomatch notify promptsubst

# The following lines were added by compinstall
zstyle :compinstall filename "/Users/jnk/.zshrc"

autoload -Uz compinit
compinit -u
# End of lines added by compinstall

zstyle ":completion:*" menu select

# personal settings
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
#export PATH:"$PATH:/Applications/microchip/xc32/v1.33/bin"

export EDITOR="vim"

alias sudo="sudo "

if [[ $(uname) == "Linux" ]]; then
	alias l="ls --color=auto"
	alias ll="ls -ah --color=auto"
	alias lll="ls -lah --color=auto"
else
	export CLICOLOR=true # ls coloured output

	alias l="ls -h"
	alias ll="ls -ah"
	alias lll="ls -lah"
fi

alias h='history -t "%T"'
alias hh='history -t "%a %d.%m.%Y %T" -D'
alias h1='history -t "%a %d.%m.%Y %T" -D -1'

alias pi="ping example.com"
alias fucking="sudo"

if [[ $(uname -m) == "x86_64" ]]; then
	alias vim="nvim"
fi

alias ghci="stack exec ghci"
alias ghc="stack exec ghc"
alias runghc="stack exec runghc"

#alias mat="matlab -nojvm -nosidplay"

bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word

# end personal settings

# custom prompt
. $HOME/.config/zsh/simple_prompt.zsh
#. $HOME/.config/zsh/disable_empty_commands.zsh

zle-keymap-select () {
	# echo $KEYMAP
	zle reset-prompt
}

zle -N zle-keymap-select
export KEYTIMEOUT=1


alias grep='grep --color=auto'

# OPAM configuration
. ${HOME}/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig

# iTerm2 shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# zsh-syntax-highlighting
if [[ -a /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
elif [[ -a /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
	source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

