# history
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt inc_append_history_time extended_history banghist histverify histfindnodups histignorespace histnostore


setopt autocd beep extendedglob nomatch notify prompt_subst
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "/Users/jnk/.zshrc"

autoload -Uz compinit
compinit -u
# End of lines added by compinstall

zstyle ":completion:*" menu select

# personal settings
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
#export PATH:"$PATH:/Applications/microchip/xc32/v1.33/bin"

export EDITOR="vim"
export VIMINIT="source $HOME/.vimrc"

alias l="ls -G"
alias ll="ls -aG"
alias lll="ls -laG"

alias h='history -t "%T"'
alias hh='history -t "%a %d.%m.%Y %T" -D'
alias h1='history -t "%a %d.%m.%Y %T" -D -1'

alias pig="ping www.google.com"
alias fucking="sudo"

alias vim="nvim"

#alias mat="matlab -nojvm -nosidplay"

bindkey "^[[1;2C" forward-word
bindkey "^[[1;2D" backward-word

# end personal settings

# custom prompt
. $HOME/.dotfiles/zsh/prompt.zsh

# disable empty commands
accept-nonempty-line () {
	if [[ -n $BUFFER ]] then
		unset RESPONSIVE_TEST
		zle reset-prompt
		zle accept-line
	else
		if [[ -z $RESPONSIVE_TEST ]] then
			RESPONSIVE_TEST=true
			RESPONSIVE_TEST_CYCLE=0
		else
			RESPONSIVE_TEST_CYCLE=$((($RESPONSIVE_TEST_CYCLE + 1) % 4))
		fi

		zle reset-prompt
	fi
}

zle -N accept-nonempty-line
bindkey "^M" accept-nonempty-line

# OPAM configuration
. ${HOME}/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# iTerm2 shell integration
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
